spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local_db?useSSL=false&allowPublicKeyRetrieval=true&socketTimeout=7000&characterEncoding=UTF-8
    username: root
    password: password
    hikari:
      auto-commit: false
      connection-timeout: 2000
      idle-timeout: 10000
      max-lifetime: 60000
      minimum-idle: 2
      maximum-pool-size: 2
  sql:
    init:
      mode: always
