spring:
  datasource:
    upd:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/local_db?useSSL=false&allowPublicKeyRetrieval=true&socketTimeout=7000&characterEncoding=UTF-8
      username: root
      password: password
      autoCommit: false
      connectionTimeout: 2000
      idleTimeout: 10000
      maxLifetime: 60000
      minimumIdle: 2
      maximumPoolSize: 2
    ref:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/local_db?useSSL=false&allowPublicKeyRetrieval=true&socketTimeout=7000&characterEncoding=UTF-8
      username: root
      password: password
      autoCommit: false
      connectionTimeout: 2000
      idleTimeout: 10000
      maxLifetime: 60000
      minimumIdle: 2
      maximumPoolSize: 2
      readOnly: true
  sql:
    init:
      mode: always
